### ISSUE TITLE
Attempting to plot close to capacity of net drive fails

### ISSUE THREAD

**Issue by Beddhist** [Blagodarenko/XPlotter#14]
When I try to plot close to the total capacity of a network drive the plotter creates too large a file:

C:\tmp\XPlotter>XPlotter_sse.exe -id 18084828890988000920 -sn 400000000 -n 14800000
14800000-t 4 -mem 6G -path z:\

XPlotter v1.0 for BURST
                programmers: Blago, Cerr Janror, DCCT

Checking directory...
Drive z:\ info:
        Name: plots4
        File system: NTFS
        Serial Number: 3178277779
        FILE_SUPPORTS_SPARSE_FILES: no
        Bytes per Sector: 512
        Sectors per Cluster: 2
The token does not have the specified privilege.
For faster writing you should restart plotter with Administrative rights.
Creating file: z:\18084828890988000920_400000000_14831352_14831352
Not enough free space, reduce "nonces"... (code = 59)

Note that -n is 14,800,000, but the number in the plot file is larger.

**Comment by Beddhist** [comment]
Same problem for 14000000.

Plotting 13000000 works, but also creates the file with the wrong number of nonces, too small this time:

C:\tmp\XPlotter>XPlotter_sse.exe -id 18084828890988000920 -sn 400000000 -n 13000000-t 4 -mem 6G -path z:\

XPlotter v1.0 for BURST
                programmers: Blago, Cerr Janror, DCCT

Checking directory...
Drive z:\ info:
        Name: plots4
        File system: NTFS
        Serial Number: 3178277779
        FILE_SUPPORTS_SPARSE_FILES: no
        Bytes per Sector: 512
        Sectors per Cluster: 2
The token does not have the specified privilege.
For faster writing you should restart plotter with Administrative rights.
Creating file: z:\18084828890988000920_400000000_1106584_1106584

**Comment by chadbaldwin** [comment]
Just happened to see your post here. I'm fairly new to this, but thought I would chime in. I'm assuming it was just a typo, but you need a space between your number of nonces and "-t", also, I would recommend you plot to a directory. Maybe it's just me, but I always have errors if I try plotting to the root of a drive.

And, I've been reading that you should use AVX if your processor architecture supports it, there's ways to find out online if your particular processor supports the AVX instruction set, I guess SSE is for older processors?

Also, how much free space is on this network drive you are plotting to? Because 14800000 nonces is just over 3.5TB. And 13000000 is just barely under 3.1TB.

Also, like the output recommends, make sure you run the plotter with admin rights, it helps. Just right click and run as Admin.

**Comment by Beddhist** [comment]
Thank you so much! You are spot on, it was a typo. I was trying to fill the disk and ran it without -n. It turns out that it tried to create a plot with about the right number of nonces, but for some reason the free space reported by Windows is not all usable.

The disk is a 4TB. Win reports total size as 3.51 TB = 3,888,694,624,256 B. Dividing this by 256*1024=1,482,752.3203125. By trial and error I have found that I can't plot 1.4 mil, but I am now plotting 1.38. Win tells me there is now 251 GB free space. Plotting 1.39 mil nonces would give me an extra 10 GB. I don't know why I can't plot the remaining 240 GB of free space.

The NAS puts another 3 or 4 partitions on all drives, so there are some more GBs wasted.

And no, I have found running the plotter as admin only means I have to map the drive in the admin window, because admin does not have access to the user's mapped drives. Once I had done that, plotting speed was HALF!

Thanks to you, I'm back in business plotting. Thank you again!

Peter.
