### ISSUE TITLE
Move switch (move after plot is finished)

### ISSUE THREAD

**Issue by Josephur** [Blagodarenko/XPlotter#24]
Can we get a switch to move the file after it's plotted (for those of us that use a scratch drive before copying to slower write SMR drives)

for instance xplotter.exe -path X:\scratch\plots -move Q:\Plots

File gets moved to Q:\Plots after the plot is completed, then program terminates

**Comment by chadbaldwin** [comment]
You could always write a batch file to do this. That's what I did. You're welcome to use mine if you'd like. Just change .txt to .bat

Open the file and update the variables to fit your needs.

Always review code prior to running it obviously. Don't trust batch files sent to you over the internet. lol.

The script checks the destination drive to see if the plot file exists, if it doesn't, then creates the plot file on the scratch drive, then moves it to the destination drive into a temporary folder, then moves it from the temporary folder into the final plot folder you specify. I did it this way in case you are mining at the same time, it eliminates the big red error message you get when the miner tries to read an incomplete file. If it the plot file already exists on destination, then it re-runs the plot command on the destination drive to make sure the file is good/complete.

The script is smart enough so that if you close it and reopen it, it will pick up where left off. 

[PlotStaging.txt](https://github.com/Blagodarenko/XPlotter/files/1670396/PlotStaging.txt)
